name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"
    paths:
      - "cv.tex"
      - "developercv.cls"
      - "assets/**"

jobs:
  release-cv-pdf:
    name: Release CV PDF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets. GITHUB_TOKEN }}
      - run: nix develop --impure --command pdflatex cv.tex
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: cv.pdf
